session_name: ws
windows:
- focus: 'true'
  layout: 265a,273x77,0,0[273x48,0,0{136x48,0,0,1,136x48,137,0,2},273x28,0,49{136x28,0,49,3,136x28,137,49,4}]
  #layout: tile
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
  - shell_command:
    - ranger
  - shell_command:
    - neofetch
  - shell_command:
    - atop 60
  window_name: main
